@echo off
echo Installing dependencies...
pip install -r requirements.txt

echo Running Amazon Core Navigation Tests...
behave features/amazon_core.feature --tags=@smoke,@functional,@ui,@integration,@browser 